# this is for local development, to test a straight docker build
# 

version: '3.6'

services:

  eagle:
    build:
      context: .
      dockerfile: container/Dockerfile
    image: eagle:latest
    ports:
      - 8080:8080