version: '3.6'
services:

  e2e:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    image: "e2e"
    container_name: e2e
    volumes:
      - reports:/testing_quality_reports/functional

#networks:
volumes:
  reports:
#    external: true